### ISSUE TITLE
Lock entities failing

### ISSUE THREAD

**Issue by J1D2A3** [Danielhiversen/home_assistant_petcare#14]
Hi,

I have the Sure Petcare integration up and running and everything works perfectly apart from locking the cat flap. It doesn't matter which lock I try to activate (all, in, or out) they all throw the following error:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/surepetcare/lock.py:88
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 12 May 2022, 23:59:33 (1 occurrences)
Last logged: 12 May 2022, 23:59:33

[139883864825472] ERROR (UN)LOCKING DEVICE - PLEASE CHECK IMMEDIATELY!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 189, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/surepetcare/lock.py", line 88, in async_lock
    await self.coordinator.lock_states_callbacks[self._lock_state](self._id)
  File "/usr/local/lib/python3.9/site-packages/surepy/client.py", line 343, in lock_in
    return await self._set_lock_state(device_id, LockState.LOCKED_IN)
  File "/usr/local/lib/python3.9/site-packages/surepy/client.py", line 373, in _set_lock_state
    raise SurePetcareError("ERROR (UN)LOCKING DEVICE - PLEASE CHECK IMMEDIATELY!")
surepy.exceptions.SurePetcareError: ERROR (UN)LOCKING DEVICE - PLEASE CHECK IMMEDIATELY!

I'm a relative beginner here so I have no idea where to start with debugging. If anyone could talk me through the next steps then I'd really appreciate it.

Many thanks.

**Comment by J1D2A3** [comment]
I've finally had my 'you're an idiot' moment with this. I'd set up a separate account to log into Sure Pet from Home Assistant and hadn't given the new account the correct permissions. As soon as I changed the permissions, Home Assistant was able to change the lock states / pet locations etc. Maybe my foolishness will be able to help someone else...
